name: Update

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a multi-line script
      run: |
        mkdir ~/.ssh/
        chmod 700 ~/.ssh/
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        git clone "$DEPLOY_REPO"
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_REPO: ${{ secrets.DEPLOY_REPO }}
