name: Update

on:
  push:
    branches:
    - leader
  schedule:
  - cron: '0 * * * *'
  repository_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        mkdir ~/.ssh/
        chmod 700 ~/.ssh/
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        cd ~
        git clone --single-branch --branch master "$DEPLOY_REPO" working
        cd working || exit -1
        echo "$HUB_KEY" > ~/.ssh/id_rsa
        git clone --single-branch --branch master "$HUB_REPO" data
        cd src || exit -1
        python3 -m main || exit -1
        cd ../data || exit -1
        git config user.name $HUB_NAME
        git config user.email $HUB_EMAIL
        git add .
        git commit -am'update' || exit 0
        git push
        
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_REPO: ${{ secrets.DEPLOY_REPO }}
        HUB_KEY: ${{ secrets.HUB_KEY }}
        HUB_REPO: ${{ secrets.HUB_REPO }}
        HUB_NAME: ${{ secrets.HUB_NAME }}
        HUB_EMAIL: ${{ secrets.HUB_EMAIL }}
